name: Ubuntu
on: 
  push:
    paths:
      - 'QtScrcpy/**'
      - '!QtScrcpy/res/**'
      - '.github/workflows/ubuntu.yml'
      - 'ci/linux/**'
  pull_request:
    paths:
      - 'QtScrcpy/**'
      - '!QtScrcpy/res/**'
      - '.github/workflows/ubuntu.yml'
jobs:
  arm64_job:
    # The host should always be Linux
    runs-on: ubuntu-22.04
    name: Build on ubuntu-22.04
    strategy:
      matrix:
        os: [ubuntu-22.04]
        qt-ver: [5.15.2]
        qt-arch-install: [aarch64]
        gcc-arch: [arm64]
    env:
      target-name: QtScrcpy
      qt-install-path: ${{ github.workspace }}/${{ matrix.qt-ver }}
      plantform-des: ubuntu
      ENV_QT_PATH: ${{ github.workspace }}/${{ matrix.qt-ver }}
    steps:
      - uses: actions/checkout@v4
      - uses: uraimo/run-on-arch-action@v2
        name: Run commands

        id: runcmd
        with:
          arch: aarch64
          distro: ubuntu22.04

          # Not required, but speeds up builds by storing container images in
          # a GitHub package registry.
          githubToken: ${{ github.token }}

          # Set an output parameter `uname` for use in subsequent steps
          run: |
            uname -a
            apt-get update
            apt-get install build-essential libgl1-mesa-dev libxkbcommon-x11-0 libpulse-dev python3-pip -y
            python3 -m pip install setuptools wheel
            python3 -m pip install py7zr==0.14.0
            python3 -m pip install aqtinstall==1.1.3
            python3 -m aqt install 5.15.2 linux_arm64 desktop -O /home/runner/work/QtScrcpy/Qt
            apt-get install -y libglew-dev libglfw3-dev
            ci/linux/build_for_linux.sh "Release"

      - name: Upload Release
        uses: actions/upload-artifact@v3.1.0
        with:
          name: QtScrcpy-${{ matrix.os }}-${{ matrix.qt-arch-install }}-Release
          path: output/x64/Release/*
      - name: Install the zip utility
        run: |
          sudo apt install zip -y
      - name: Zip the Artifacts
        run: |
          zip -r QtScrcpy-${{ matrix.os }}-${{ matrix.qt-arch-install }}.zip output/x64/Release
      - name: Upload to Releases
        if: startsWith(github.ref, 'refs/tags/')
        
        uses: svenstaro/upload-release-action@2.3.0
        with:
          file: QtScrcpy-${{ matrix.os }}-${{ matrix.qt-arch-install }}.zip
          asset_name: QtScrcpy-${{ matrix.os }}-${{ matrix.qt-arch-install }}.zip
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          overwrite: true
